books/urls.py
from django.urls import path
from books import views as books_views

app_name = 'books'

urlpatterns = [
    path(
        route='',
        view=books_views.BookListView.as_view(),
        name='book-list' 
    ),
    path(
        route='book/<slug:slug>/',
        view=books_views.BookDetailView.as_view(),
        name='book-detail' 
    ),
    path(
        route='book/<slug:book_slug>/<int:chapter_number>/',
        view=books_views.BookChapterDetailView.as_view(),
        name='chapter-detail', 
    ),
     path(
        route='book/<slug:book_slug>/<int:chapter_number>/<int:exercise_number>',
        view=books_views.BookExerciseDetailView.as_view(),
        name='exercise-detail', 
    ),
]

shopping_cart/urls.py
from django.urls import path
from shopping_cart import views as shopping_cart_views

app_name = 'shopping_cart'

urlpatterns = [
    path(
        'add-to-cart/<slug:book_slug>/', 
        shopping_cart_views.AddToCartView.as_view(),
        name='add-to-cart'
    ),
    path(
        'remove-from-cart/<slug:book_slug>/', 
        shopping_cart_views.RemoveFromCartView.as_view(),
        name='remove-from-cart'
    ),
    path(
        'order-summary/',
        shopping_cart_views.OrderSummaryView.as_view(),
        name='order-summary'
    ),
    path(
        'checkout/',
        shopping_cart_views.CheckOutView.as_view(),
        name='checkout'
    ),
    path(
        'webhook/',
        shopping_cart_views.webhook,
        name='webhook'
    )
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from digital_marketplace.utils.managers import CustomUserManager



# Create your models here.
class CustomUser(AbstractUser):
    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    objects = CustomUserManager()

    email = models.EmailField(unique=True, max_length=40)


    def __str__(self):
        return self.get_full_name() or self.email
    

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from home.models import CustomUser


class SignupForm(UserCreationForm):
    first_name = forms.CharField(
        label="First name",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'First name',
                'required': True,
            }
        )
    )
    last_name = forms.CharField(
        label="Last name",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Last name',
                'required': True,
            }
        )
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password'
            }
        ),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirm Password'
            }
        ),
        strip=False,
    )
    class Meta:
        model = CustomUser
        fields = [
                'first_name',
                'last_name',
                'email',
                'username',
                'password1',
                'password2'
            ]

        help_texts = {
                    "username":""
                }

        widgets = {  
            'email': forms.EmailInput(
                attrs={
                'placeholder': 'Email address',
            }),
            'username': forms.TextInput(
                attrs={
                'placeholder': 'Username',
            }),
        }

    # def __init__(self, *args, **kwargs):
    #     super(RegistrationForm, self).__init__(*args, **kwargs)
    #     for name, field in self.fields.items():
    #         # print(field.widget)
    #         if name == "first_name":
    #             field.widget.attrs.update({'placeholder':'First Name'})
    #             field.required = True
    #         elif name == "last_name":
    #             field.widget.attrs.update({'placeholder':'Last Name'})
    #             field.required = True

    #         elif name == "email":
    #             field.widget.attrs.update({'placeholder':'Email Address'})
    #         elif name == "username":
    #             field.widget.attrs.update({'placeholder':'Username'})
    #         elif name == "password1":
                # field.widget.attrs.update({'placeholder':'Password'})
            # elif name == "password2":
                # field.widget.attrs.update({'placeholder':'Confirm Password'})
            

home/views.py
from django.shortcuts import render

# Create your views here.

home/templates/partials/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ebooks Solutions | {% block title %}{% endblock title %}</title>
    {% include 'partials/_stylesheets.html' %}
    {% block stylesheets %}
    {% endblock stylesheets %}
</head>
<body>
    {% include 'partials/_navbar.html' %}

    <main class="container">

        {% block body %}    

        
        {% endblock body %}

    </main>
    
    {% include 'partials/_scripts.html' %}
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

home/templates/partials/_breadcrumb.html
{% comment %} <div class="bg-light p-2 shadow-sm">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Library</a></li>
            <li class="breadcrumb-item active" aria-current="page">Data</li>
        </ol>
    </nav>
</div> {% endcomment %}

{% comment %} <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
    </ol>
    </nav> {% endcomment %}

home/templates/partials/_navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Offcanvas navbar</a>
      <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'books:book-list' %}">Books</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link position-relative" href="{% url 'shopping_cart:order-summary' %}">
              <i class="bi bi-cart"></i>
                <span class="position-absolute top-5 start-100 translate-middle p-2 badge bg-secondary">
                  {{ request.user|cart_item_count }}
                  <span class="visually-hidden"></span>
                </span>
            </a>
          </li>
          <li class="nav-item px-3">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

home/templates/partials/_scripts.html
{% load static %}
{% comment %} <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script> {% endcomment %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/offcanvas.js' %}"></script>



<script>
    const url = document.querySelector('a[href="{{request.path}}"]');
    if (url){
        url.classList.add('active');
    }
</script>

home/templates/partials/_stylesheets.html
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">