books/urls.py
from django.urls import path
from books import views as books_views

app_name = 'books'

urlpatterns = [
    path(
        route='',
        view=books_views.BookListView.as_view(),
        name='book-list' 
    ),
    path(
        route='book/<slug:slug>/',
        view=books_views.BookDetailView.as_view(),
        name='book-detail' 
    ),
    path(
        route='book/<slug:book_slug>/<int:chapter_number>/',
        view=books_views.BookChapterDetailView.as_view(),
        name='chapter-detail', 
    ),
     path(
        route='book/<slug:book_slug>/<int:chapter_number>/<int:exercise_number>',
        view=books_views.BookExerciseDetailView.as_view(),
        name='exercise-detail', 
    ),
]

shopping_cart/urls.py
from django.urls import path
from shopping_cart import views as shopping_cart_views

app_name = 'shopping_cart'

urlpatterns = [
    path(
        'add-to-cart/<slug:book_slug>/', 
        shopping_cart_views.AddToCartView.as_view(),
        name='add-to-cart'
    ),
    path(
        'remove-from-cart/<slug:book_slug>/', 
        shopping_cart_views.RemoveFromCartView.as_view(),
        name='remove-from-cart'
    ),
    path(
        'order-summary/',
        shopping_cart_views.OrderSummaryView.as_view(),
        name='order-summary'
    ),
    path(
        'checkout/',
        shopping_cart_views.CheckOutView.as_view(),
        name='checkout'
    ),
    path(
        'webhook/',
        shopping_cart_views.webhook,
        name='webhook'
    )
]

shopping_cart/models.py
import auto_prefetch
from django.db import models
from django.db.models import Sum
from digital_marketplace.utils.models import TimeBasedModel
from digital_marketplace.utils.choices import OrderStatus, PaymentStatus
# Create your models here.

class Order(TimeBasedModel):
    user = auto_prefetch.ForeignKey(
        "home.CustomUser",
        on_delete=models.CASCADE
    )
    status = models.CharField(
        max_length=15,
        choices=OrderStatus.choices, 
        default=OrderStatus.Pending
    )
    items = models.ManyToManyField("shopping_cart.OrderItem", blank=True)
    ref_code = models.CharField(max_length=50, blank=True)

    def get_total(self):
        return self.items.all().aggregate(order_total=Sum("book__price"))['order_total']

    def __str__(self):
        return f"{self.user} Order"
    

class OrderItem(TimeBasedModel):
    book = auto_prefetch.ForeignKey(
        "books.Book",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.book.name
    
class Payment(TimeBasedModel):
    order = auto_prefetch.ForeignKey(
        "shopping_cart.Order",
        on_delete=models.CASCADE,
    )
    status = models.CharField(
        max_length=50, 
        choices=PaymentStatus.choices,
        default=PaymentStatus.Pending
    )
    total_amount = models.FloatField(blank=True, null=True)
    transaction_id = models.CharField(max_length=100, blank=True)
    raw_response = models.TextField(blank=True)


    def __str__(self):
        return f"{self.order} - {self.transaction_id} Payment"
    

shopping_cart/views.py
import json
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import View, TemplateView

from books.models import Book
from shopping_cart.models import Order, OrderItem, Payment

from digital_marketplace.utils.choices import OrderStatus
from digital_marketplace.utils.hash import shaEncryption
from digital_marketplace.utils.env_variable import get_env_variable
from digital_marketplace.utils.api import verify_user_transactions
from digital_marketplace.utils.choices import PaymentStatus

# Create your views here.


class AddToCartView(LoginRequiredMixin, View):

    def get(self, request, book_slug):
        book = get_object_or_404(Book, slug=book_slug)
        order_item, created = OrderItem.objects.get_or_create(book=book)
        order, _ = Order.objects.get_or_create(user=request.user, status=OrderStatus.Pending)
        order.items.add(order_item)
        order.save()

        return redirect(request.META.get('HTTP_REFERER'))
    

class RemoveFromCartView(LoginRequiredMixin, View):

    def get(self, request, book_slug):
        book = get_object_or_404(Book, slug=book_slug)
        order_item = get_object_or_404(OrderItem, book=book)
        order = get_object_or_404(Order, user=request.user, status=OrderStatus.Pending)
        order.items.remove(order_item)
        order.save()

        return redirect(request.META.get('HTTP_REFERER'))
    

class OrderSummaryView(LoginRequiredMixin, TemplateView):
    template_name = 'shopping_cart/order_summary.html'

    # def get_object(self):
    #     object = get_object_or_404(Order, user=self.request.user, status=OrderStatus.Pending)
    #     return object
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request = self.request
        order = None
        try:
            order = Order.objects.get(user=self.request.user, status=OrderStatus.Pending)
        except:
            pass
        secret_key = get_env_variable('FLUTTERWAVE_SECRET_KEY')
        hashed_secret_key = shaEncryption(secret_key)
        string_to_be_hashed = (
            str(order.get_total()) + "NGN" + request.user.email + order.ref_code + hashed_secret_key
        )
        payload_hash = shaEncryption(string_to_be_hashed)
        public_key = get_env_variable('FLUTTERWAVE_PUBLIC_KEY')

        context.update({
            'order': order,
            'public_key': public_key,
            'ref_code': order.ref_code,
            'payload_hash': payload_hash
        })
        return context
    

class CheckOutView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, user=self.request.user,status=OrderStatus.Pending)

        """
            do flutterwave stuff
        """

        payment, _ = Payment.objects.get_or_create(order=order)
        transaction_id = request.GET.get('transaction_id')
        payment.transaction_id = transaction_id
        payment.total_amount = order.get_total()
        payment.save()
        response = verify_user_transactions(transaction_id)

        if response['data']['status'] == 'successful' and \
        response['data']['amount'] == order.get_total() and \
        response['data']['currency'] == 'NGN':
            payment.status = PaymentStatus.Successful
            payment.raw_response = response
            payment.save()

            books_in_order = [item.book for item in order.items.all()]
            for book in books_in_order:
                request.user.userlibrary.books.add(book)
            
            order.status = OrderStatus.Completed
            order.save()

            messages.success(request, "Payment made successfully")
            return redirect("books:book-list")
    
            
        payment.status = PaymentStatus.Failed
        payment.save()
        messages.error(request, "Payment failed")
        return redirect("books:book-list")


@require_POST
@csrf_exempt
def webhook(request):
    secret_hash = get_env_variable("FLUTTERWAVE_SECRET_HASH")
    signature = request.headers.get("Verif-Hash")
    if signature is None or signature != secret_hash:
        return HttpResponse(status=401)
    payload = json.loads(request.body)
    existing_payment = Payment.objects.get(transaction_id=payload.get('id'))
    if existing_payment.status == payload.get('status'):
        return HttpResponse(status=200)
    existing_payment.status = payload.get('status')
    existing_payment.save()
    HttpResponse(status=200)

shopping_cart/templates/shopping_cart/order_summary.html
{% extends 'partials/_base.html' %}
{% block title %}Order Summary{% endblock title %}
{% block body %}
<h1>Order Summary</h1>
<table class="table text-center table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{item.book.title}}</td>
              <td>${{item.book.price}}</td>
              <td><a href="{% url 'shopping_cart:remove-from-cart' item.book.slug %}"><i class="bi bi-trash text-danger"></i></a></td>
            </tr>
        {% empty%}
            <tr>
              <td colspan="4">
                  There are no items in your cart
              </td>
            </tr>
        {% endfor %}
        {% if order.get_total %}
        <tr>
          <td colspan="3">
            <strong>Total order: </srong>
          </td>
          <td colspan="1">
            <strong>${{order.get_total}} </srong>
          </td>
        </tr>
        {% endif %}
        <tr>
            <td colspan="4">
                <a href="{% url 'books:book-list' %}" class="btn btn-warning">
                  {% if order %}
                    Continue shopping
                  {% else %}
                    Add items to your cart
                  {% endif %}
                </a>
            </td>
        </tr>
        {% if order.get_total %}
        <tr>
          <td colspan="4">
              <button type="button" class="btn btn-primary" onclick="makePayment()">Pay Now</button>
          </td>
      </tr>
      {% endif %}

    </tbody>
  </table>
{% endblock body %}

{% block scripts %}
<script src="https://checkout.flutterwave.com/v3.js"></script>

<script>
function makePayment() {
    FlutterwaveCheckout({
      public_key: "{{public_key}}",
      tx_ref: "{{ref_code}}",
      amount: "{{order.get_total}}",
      currency: "NGN",
      payment_options: "card",
      redirect_url: "https://c1b1-105-112-47-177.ngrok-free.app/cart/checkout/",
      onclose: function(incomplete) {
        if (incomplete === true) {
          message: "Payment cancelled"
        }
      },
      meta: {
        consumer_id: 23,
        consumer_mac: "92a3-912ba-1192a",
      },
      customer: {
        email: "{{request.user.email}}",
        phone_number: "08102909304",
        name: "{{request.user.get_full_name}}",
      },
      customizations: {
        title: "Digital Marketplace",
        description: "Your number one book solutions",
        logo: "https://www.logolynx.com/images/logolynx/22/2239ca38f5505fbfce7e55bbc0604386.jpeg",
      },
     payload_hash: "{{payload_hash}}"
    });
  }
</script>
{% endblock scripts %}