books/urls.py
from django.urls import path
from books import views as books_views

app_name = 'books'

urlpatterns = [
    path(
        route='',
        view=books_views.BookListView.as_view(),
        name='book-list' 
    ),
    path(
        route='book/<slug:slug>/',
        view=books_views.BookDetailView.as_view(),
        name='book-detail' 
    ),
    path(
        route='book/<slug:book_slug>/<int:chapter_number>/',
        view=books_views.BookChapterDetailView.as_view(),
        name='chapter-detail', 
    ),
     path(
        route='book/<slug:book_slug>/<int:chapter_number>/<int:exercise_number>',
        view=books_views.BookExerciseDetailView.as_view(),
        name='exercise-detail', 
    ),
]

books/models.py
import auto_prefetch
from django.conf import settings
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse
from digital_marketplace.utils.models import (
    NamedTimeBasedModel, TimeBasedModel
)
from digital_marketplace.utils.media import (
    book_image_upload_path, solution_image_upload_path
)

# Create your models here.

class UserLibrary(TimeBasedModel):
    user = auto_prefetch.OneToOneField(
        "home.CustomUser",
        on_delete=models.CASCADE,
    )
    books = models.ManyToManyField('Book', blank=True)

    def book_list(self):
        return self.books.all()

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = "User Library"
        verbose_name_plural = "User Library"

    def __str__(self):
        return f"{self.user} - Library"
    
    
class Author(NamedTimeBasedModel):
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name
    

class Book(NamedTimeBasedModel):
    author = models.ManyToManyField(Author)
    isbn = models.CharField(max_length=216)
    cover_image = models.ImageField(
        # default="",
        upload_to=book_image_upload_path,
        blank=True,
    )
    slug = models.SlugField(unique=True, blank=True)
    price = models.FloatField()

    def cover_image_url(self):
        if self.cover_image:
            return self.cover_image.url
            
        return f"{settings.MEDIA_URL}/default/book.png"

    def get_absolute_url(self):
        return   reverse("books:book-detail", kwargs={"slug": self.slug})
    
    def __str__(self):
        return self.name


class Chapter(NamedTimeBasedModel):
    book = auto_prefetch.ForeignKey(
        'books.Book',
        on_delete=models.CASCADE
    )
    chapter_number = models.PositiveSmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse("books:chapter-detail", 
            kwargs={
                "book_slug": self.book.slug,
                "chapter_number": self.chapter_number
            }
        )
    

    def __str__(self):
        return self.name
    
class Exercise(NamedTimeBasedModel):
    chapter = auto_prefetch.ForeignKey(
        'books.Chapter',
        on_delete=models.CASCADE
    )
    exercise_number = models.PositiveSmallIntegerField(default=0)
    page_number = models.PositiveSmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse("books:exercise-detail", 
            kwargs={
                "book_slug": self.chapter.book.slug,
                "chapter_number": self.chapter.chapter_number,
                "exercise_number": self.exercise_number
            }
        )

    def __str__(self):
        return self.name


class Solution(models.Model):
    exercise = auto_prefetch.ForeignKey(
        Exercise,
        on_delete=models.CASCADE
    )
    solution_number = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(
        upload_to=solution_image_upload_path
    )

    def __str__(self):
        return f"Solution to {self.exercise.name}"
    
    def image_url(self):
        if self.image:
            return self.image.url
            
        return f"{settings.MEDIA_URL}/default/book.png"
    

    def image_url(self):
        if self.image_url:
            return self.image.url
            
        return f"{settings.MEDIA_URL}/default/book.png"

books/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    DetailView, ListView, View
)
from books.models import ( 
    Book, Chapter, Exercise, Solution
)
from shopping_cart.models import Order, OrderItem
from digital_marketplace.utils.helpers import check_book_relationship

# Create your views here.
class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 25
    template_name = 'books/book_list.html'

    
class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'books/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.object
        request = self.request
        book_status = check_book_relationship(request, book)
        context.update({
            'book_status':book_status
        }) 
        return context

class BookChapterDetailView(DetailView):
    model = Chapter
    context_object_name = 'chapter'    
    template_name = 'books/book_chapter_detail.html'
    query_pk_and_slug = True
    slug_field = 'book__slug'
    slug_url_kwarg = 'book_slug'
    pk_url_kwarg = 'chapter_number'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chapter = self.object
        request = self.request
        book_status = check_book_relationship(request, chapter.book)
        context.update({
            'book_status':book_status
        }) 
        return context


class BookExerciseDetailView(View):

    def get(self, request, book_slug, chapter_number, exercise_number):
        exercise = get_object_or_404(
            Exercise, 
            chapter__book__slug=book_slug,
            chapter__chapter_number=chapter_number,
            exercise_number=exercise_number,
        )
        request = self.request
        book_status = check_book_relationship(request, exercise.chapter.book)
        context = {
            "exercise": exercise,
            'book_status':book_status
        }
        return render(request, 'books/book_exercise_detail.html', context)

books/templates/books/book_chapter_detail.html
{% extends 'partials/_base.html' %}
{% block title %}{{chapter.title}}{% endblock title %}
{% block body %}
{% block breadcrumb %}
<div class="bg-light p-2 mt-2 shadow-sm">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'books:book-list' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{book.get_absolute_url}}">{{chapter.book.title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{chapter.title}}</li>

        </ol>
    </nav>
</div>
{% endblock breadcrumb %}
<div class="row my-5">
    <div class="col-md-5">
        {% include 'books/partials/_book_detail.html' with book=chapter.book %}
    </div>

    <div class="col-md-7">
        <div class="card">
            <div class="card-header">
              Exercises
            </div>
            <ul class="list-group list-group-flush">
              {% for exercise in chapter.exercise_set.all %}
              <li class="list-group-item"><a href="{{exercise.get_absolute_url}}">{{exercise.exercise_number}}. {{exercise.title}}</a></li>
          {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock body %} 

books/templates/books/book_detail.html
{% extends 'partials/_base.html' %}
{% block title %}{{book.title}}{% endblock title %}
{% block body %}
{% block breadcrumb %}
<div class="bg-light p-2 mt-2 shadow-sm">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'books:book-list' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{book.title}}</li>
        </ol>
    </nav>
</div>
{% endblock breadcrumb %}  

<div class="row my-5">
    <div class="col-md-5">
        {% include 'books/partials/_book_detail.html' with book=book %}
    </div>

    <div class="col-md-7">
        <div class="card">
            <div class="card-header">
              Chapters
            </div>
            <ul class="list-group list-group-flush">
              {% for chapter in book.chapter_set.all %}
              <li class="list-group-item"><a href="{{chapter.get_absolute_url}}">{{chapter.chapter_number}}. {{chapter.title}}</a></li>
          {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock body %} 

books/templates/books/book_exercise_detail.html
{% extends 'partials/_base.html' %}
{% load static %}
{% block title %}{{exercise.title}}{% endblock title %}
{% block body %}
{% block breadcrumb %}
<div class="bg-light p-2 mt-2 shadow-sm">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'books:book-list' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{exercise.chapter.book.get_absolute_url}}">{{exercise.chapter.book.title}}</a></li>
            <li class="breadcrumb-item"><a href="{{exercise.chapter.get_absolute_url}}">{{exercise.chapter.title  }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{exercise.title}}</li>
        </ol>
    </nav>
</div>
{% endblock breadcrumb %}    
<div class="row my-5">
    <div class="col-md-5">
        {% include 'books/partials/_book_detail.html' with book=exercise.chapter.book %}

    </div>

    <div class="col-md-7">
        <div class="card">
            <div class="card-header">
              Solution
            </div>
            <div class="accordion accordion-flush" id="accordionFlushExample">
                {% if book_status == "owned" %}
                    {% for solution in exercise.solution_set.all %}
                        <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{solution.solution_number}}" aria-expanded="false" aria-controls="flush-collapseOne">
                                Solution #{{solution.solution_number}}
                            </button>
                        </h2>
                        <div id="flush-collapse{{solution.solution_number}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne">
                            <div class="accordion-body">
                                <img src="{{solution.image_url}}" class="img-fluid">
                            </div>
                        </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="text-center">
                        <h4>You do not have access to this book.
                            to have access to the solutions<h3>
                        <img class="img-fluid" src="{% static 'images/lock.png' %}" width="200px" height="300px">
                    </div>
                {% endif %}
              </div>
    </div>

</div>
{% endblock %}

books/templates/books/book_list.html
{% extends 'partials/_base.html' %}
{% block title %}Books{% endblock title %}
{% block body %}
{% block breadcrumb %}

<div class="bg-light p-2 my-2 shadow-sm">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Books</li>

        </ol>
    </nav>
</div>
{% endblock breadcrumb %}
<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for book in books %}
        <div class="col">
            <div class="card h-100">
                <img src="{{book.cover_image_url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{book.get_absolute_url}}" class="card-link">{{book.title}}</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{book.created_at|date:'jS M, Y.'}}</h6>
                    <p class="card-text">
                        {% for author in book.author.all %}
                            <span>{{author}}</span>
                                {% if book.author.count > 1 %}|{% endif %}
                        {% endfor %}
                    </p>
                    
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock body %}